version: 2.1
orbs:
  docker: circleci/docker@2.2.0

workflows:
  build-docker-image:
    jobs:
      - docker/publish:
          image: ministryofjustice/fb-builder
          tag: 'latest'
          filters:
            branches:
              only:
                - main
                - master
                
