version: 2.1
orbs:
  docker: circleci/docker@2.2.0

workflows:
  build-docker-image-only:
    jobs:
      - docker/publish:
          context:
            - moj-forms
          deploy: false
          image:  ministryofjustice/fb-builder
          filters:
            branches:
              ignore:
                - main
                - master

  build-docker-image:
    jobs:
      - docker/publish:
          context:
            - moj-forms
          image: ministryofjustice/fb-builder
          tag: 'latest'
          filters:
            branches:
              only:
                - main
                - master

